# -*- coding: utf-8 -*-
"""potato disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtKpEl_G8YeGFLw9NMk1rLWYbL5ut_iw
"""

import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))

import os

base_path = "/content/drive/MyDrive/Patato Disease"

for split in ["Train", "Valid", "Test"]:
    path = os.path.join(base_path, split)

    print("\n", split)
    print(os.listdir(path))

import os

base_path = "/content/drive/MyDrive/Patato Disease"

for split in ["Train", "Valid", "Test"]:
    print(f"\n===== {split} =====")

    split_path = os.path.join(base_path, split)

    for class_name in os.listdir(split_path):
        class_path = os.path.join(split_path, class_name)

        if os.path.isdir(class_path):
            count = len(os.listdir(class_path))
            print(f"{class_name}: {count}")

import matplotlib.pyplot as plt
import os
from PIL import Image

base_path = "/content/drive/MyDrive/Patato Disease/Train"

classes = os.listdir(base_path)

plt.figure(figsize=(12, 8))

for i, class_name in enumerate(classes):

    class_path = os.path.join(base_path, class_name)

    image_name = os.listdir(class_path)[0]
    image_path = os.path.join(class_path, image_name)

    image = Image.open(image_path)

    plt.subplot(1, 3, i + 1)
    plt.imshow(image)
    plt.title(class_name)
    plt.axis("off")

plt.show()

import tensorflow as tf

base_path = "/content/drive/MyDrive/Patato Disease"

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_data = tf.keras.utils.image_dataset_from_directory(
    f"{base_path}/Train",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True
)

valid_data = tf.keras.utils.image_dataset_from_directory(
    f"{base_path}/Valid",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_data = tf.keras.utils.image_dataset_from_directory(
    f"{base_path}/Test",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print("Classes:", train_data.class_names)

images, labels = next(iter(train_data))

print("Image batch shape:", images.shape)
print("Label batch shape:", labels.shape)
print("First 10 labels:", labels[:10].numpy())

print("Data type:", images.dtype)

print("\nOne pixel:")
print(images[0, 0, 0])

print("\nFirst 5 x 5 pixels:")
print(images[0, :5, :5])

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.1),
    tf.keras.layers.RandomZoom(0.1)
])

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 10))

for images, labels in train_data.take(1):

    for i in range(9):

        augmented_image = data_augmentation(images[i])

        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(augmented_image.numpy().astype("uint8"))
        plt.title(train_data.class_names[labels[i]])
        plt.axis("off")

plt.show()

!pip install -q tensorflow-hub

import tensorflow_hub as hub
import tensorflow as tf

MODEL_URL = "https://tfhub.dev/tensorflow/efficientnet/b0/feature-vector/1"

feature_extractor = hub.KerasLayer(
    MODEL_URL,
    input_shape=(224, 224, 3),
    trainable=False
)

feature_extractor = hub.KerasLayer(
    MODEL_URL,
    input_shape=(224, 224, 3),
    trainable=False
)

images, labels = next(iter(train_data))

features = feature_extractor(images[:1])

print("Feature shape:", features.shape)

images, labels = next(iter(train_data))

images = images / 255.0

features = feature_extractor(images[:1])

print("Input shape:", images[:1].shape)
print("Feature shape:", features.shape)

def extract_features(dataset):
    all_features = []
    all_labels = []

    for images, labels in dataset:
        images = images / 255.0

        features = feature_extractor(images)

        all_features.append(features.numpy())
        all_labels.append(labels.numpy())

    return np.concatenate(all_features), np.concatenate(all_labels)

import numpy as np

X_train_features, y_train = extract_features(train_data)

print("Feature shape:", X_train_features.shape)
print("Label shape:", y_train.shape)

X_valid_features, y_valid = extract_features(valid_data)

X_test_features, y_test = extract_features(test_data)

print("Validation feature shape:", X_valid_features.shape)
print("Validation label shape:", y_valid.shape)

print("Test feature shape:", X_test_features.shape)
print("Test label shape:", y_test.shape)

classifier = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(1280,)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(3, activation="softmax")
])

classifier.summary()

classifier.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

history = classifier.fit(
    X_train_features,
    y_train,
    validation_data=(X_valid_features, y_valid),
    epochs=20,
    batch_size=32
)

test_loss, test_accuracy = classifier.evaluate(
    X_test_features,
    y_test
)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

y_pred_probs = classifier.predict(X_test_features)

y_pred = np.argmax(y_pred_probs, axis=1)

print("First 20 actual labels:")
print(y_test[:20])

print("\nFirst 20 predicted labels:")
print(y_pred[:20])

from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred,
    target_names=train_data.class_names
))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

print(cm)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(7, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=train_data.class_names,
    yticklabels=train_data.class_names
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Potato Disease Confusion Matrix")
plt.show()

classifier.save(
    "/content/drive/MyDrive/Patato Disease/potato_classifier.keras"
)

import os

model_path = "/content/drive/MyDrive/Patato Disease/potato_classifier.keras"

print("Model saved:", os.path.exists(model_path))

import tensorflow as tf
import numpy as np

class_names = train_data.class_names

def predict_disease(image_path):

    # Load image
    image = tf.keras.utils.load_img(
        image_path,
        target_size=(224, 224)
    )

    # Convert image to array
    image = tf.keras.utils.img_to_array(image)

    # Add batch dimension
    image = np.expand_dims(image, axis=0)

    # Scale pixels from 0-255 to 0-1
    image = image / 255.0

    # Extract EfficientNet features
    features = feature_extractor(image)

    # Classifier prediction
    probabilities = classifier.predict(features, verbose=0)

    # Get highest probability
    predicted_class = np.argmax(probabilities[0])
    confidence = probabilities[0][predicted_class]

    print("Prediction:", class_names[predicted_class])
    print("Confidence:", round(float(confidence) * 100, 2), "%")

import glob

test_images = glob.glob(
    "/content/drive/MyDrive/Patato Disease/Test/*/*.JPG"
)

print("Number of images:", len(test_images))
print("First image:", test_images[0])

predict_disease(test_images[0])

@tf.function(
    input_signature=[
        tf.TensorSpec(shape=[None, 224, 224, 3], dtype=tf.float32)
    ]
)
def serving_model(images):

    # EfficientNet feature extraction
    features = feature_extractor(images / 255.0)

    # Classification
    probabilities = classifier(features)

    return probabilities

test_batch = tf.convert_to_tensor(
    images[:2],
    dtype=tf.float32
)

predictions = serving_model(test_batch)

print("Prediction shape:", predictions.shape)
print(predictions)

images_test, labels_test = next(iter(test_data))

predictions = serving_model(
    tf.cast(images_test[:2], tf.float32)
)

print("Prediction shape:", predictions.shape)
print(predictions)

class PotatoDiseaseModel(tf.Module):

    def __init__(self, feature_extractor, classifier):
        super().__init__()
        self.feature_extractor = feature_extractor
        self.classifier = classifier

    @tf.function(
        input_signature=[
            tf.TensorSpec(
                shape=[None, 224, 224, 3],
                dtype=tf.float32
            )
        ]
    )
    def predict(self, images):

        # Convert 0-255 → 0-1
        images = images / 255.0

        # EfficientNet features
        features = self.feature_extractor(images)

        # Disease prediction
        probabilities = self.classifier(features)

        return probabilities


potato_model = PotatoDiseaseModel(
    feature_extractor,
    classifier
)

save_path = "/content/drive/MyDrive/Patato Disease/potato_disease_model"

tf.saved_model.save(
    potato_model,
    save_path,
    signatures={
        "serving_default": potato_model.predict
    }
)

print("Model saved successfully!")

loaded_model = tf.saved_model.load(
    "/content/drive/MyDrive/Patato Disease/potato_disease_model"
)

print("Model loaded successfully!")

predictions = loaded_model.predict(
    tf.cast(images_test[:1], tf.float32)
)

print("Prediction shape:", predictions.shape)
print("Prediction:", predictions.numpy())

predicted_class = np.argmax(predictions.numpy()[0])
confidence = predictions.numpy()[0][predicted_class]

print("Prediction:", class_names[predicted_class])
print("Confidence:", round(float(confidence) * 100, 2), "%")

import shutil

source = "/content/drive/MyDrive/Patato Disease/potato_disease_model"
output = "/content/potato_disease_model"

shutil.make_archive(
    output,
    "zip",
    source
)

print("ZIP created successfully!")

from google.colab import files

files.download("/content/potato_disease_model.zip")

